services:
  transformer-service:
    container_name: transformer-service
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    volumes:
      - ./target:/app/target
